### ISSUE TITLE
Implement flag groups

### ISSUE THREAD

**Issue by mcmdev** [ReflxctionDev/cub#1]
Flag groups are a feature which allows switches and flags to be combined.
Example:
Lets say I have a command with a switch called A, a switch called B and a flag called C of type string
Usually I'd have to type it like the following: `mycommand -a -b -c myString`
With flag groups, it can be typed like this: 
`mycommand -abc myString` or like this `mycommand -ac myString -b`
So in a flag group, switches can be combined and typed right after one another and a flag can be put at the end of the group taking the next value as well.
If needed, I can explain it further.

**Comment by Revxrsal** [comment]
Unfortunately I don't believe implementing this feature would be feasible. Combining this with having to support tab-completions for flag groups will require lots of edge cases and hard-coded rules (at least from what I believe). 

Since users can now auto-complete flags, I don't think such hassle has to be carried on to reduce a few more characters 😛
